### PR TITLE
Add setup.py

### LINKED ISSUE #1: Add a setup.py
i am interested to make your project wonderfull i will make a setup.py
which will do

*make the project available through commandline and desktop menu
without affecting the current project.if you are interetsted post a reply

PS(IT WILL WORK ONLY WITH LINUX)

### PR DESCRIPTION
**Pull request by Painadath**
Hey i have added a setup.py and additional requirements.tested on raspberry pi4 on RaspBian
if you want to check the updates download my fork repo https://github.com/Painadath/Fedit
go to the root folder and type sudo  python3 setup.py install 
PS(as a local library is complicted as of my vision i haved merged your library with the main program )
any problems report at samuelpainadath@gmail.com

### CODE REVIEW

**Comment by Painadath** [comment]
You have to merge this after testing

**Comment by Pythonic456** [comment]
There seems to be some problems with the setup.py, the desktop file when installed doesn't work, saying that it is an invalid file.

As of now I will be keeping the tktools.py as a separate file, but other than that :)
Thanks :)

**Comment by Pythonic456** [comment]
What is setup.py meant to achieve? It seems to build an egg, which seems unnecessary to me. And then it doesn't seem to do much after that except adding it to the Menu. And I had to change a few things in setup.py before it worked. Was this meant to run with the binary or am I missing something?

**Comment by Painadath** [comment]
Sorry it worked for me why I removed the tktools.py was something went wrong.only with this project .there is a my project called pyencrypter which was my first project. github.com/Painadath/ but it worked also with a local library but I couldn't figure out this problem

**Comment by Painadath** [comment]
PS on which Linux you have tried and could you please handle me the problems I repeat there is no problem with my raspberry pi

**Comment by Painadath** [comment]
And could you please read the file in the bin I HAVE INCLUDE D ALL THE FILES IN THE tktools.py and it doesn't hurt the performance

**Comment by Painadath** [comment]
As you have mentioned I have tried this on my raspberry pi 3 with Ubuntu mate 18.04 but there is no problem.neither in menu nor in commandline

**Comment by Painadath** [comment]
This is what the setup.py do.copying the file in the bin folder to 0usr/local/bin and make it executable 

and the desktop file to /usr/share/applications and icon to /usr/share/pixmaps it doesn't need the binary to work after installing

**Comment by Painadath** [comment]
Dude it worked I will close this and open another PR
It fully worked with the local library and now you can keep the tktools.py as a separate file

**Pull request closed without merging**
