### PR TITLE
Add a setup.py

### PR DESCRIPTION
**Pull request by Painadath**
I have created another file and it will work with the local lib check it out on 
https://github.com/Painadath/Fedit

### CODE REVIEW

**Comment by Pythonic456** [comment]
I want this project to remain as neat as possible, why can't tktools.py and main.py be in the same directory? And why do we have to have more folders for stuff that is already there?
(PS: These are genuine questions and I am thankful for your support 👍 )

**Comment by Painadath** [comment]
I will explain it beacuase if we put the files which go to bin in bin folder it will easy to the people who view over this project .and why I separated it tktools is local library and after installing this project you can access this library from any location of the Linux computer.on yours previous project it will work only if the main.py and tktools.py are in the same directory .and now if you look at /usr/local/bin/fedit it is the file which generated by easy install.

**Comment by Pythonic456** [comment]
It is not necessary to be able to access tktools.py from anywhere on the system, all I would like is a single setup.py script that doesn't need to change the whole layout of the project. If you can do a _single_ script which will set it up without making directories and moving files, great! Then you will be mentioned in this project for helping what it will be.

As always, thanks for your help and cooperation 👍

**Comment by Painadath** [comment]
Ok then I will write the setup.py to move the complete project to usr/share/fedit and edit the desktop file to access all from there .is this okay?

**Comment by Painadath** [comment]
Or do you mean that don't move any of the project files and just install the desktop entry

**Comment by Pythonic456** [comment]
I think (this is just my personal opinion) that just creating the Desktop entry would be the nicest and most user-friendly way, but also means that if the user deletes the files then Fedit won't start at all. Maybe the setup script could ask which one you would like to do?

PS. Before you do another PR please update your repo as it is ~6 commits behind mine 👍

**Comment by Painadath** [comment]
Ok I have checked your mention and will work on it and if the user deletes the directory the desktop entry remains so there will be a non useful item in the menu.i think we could add another option called remove my in setup.py .which will deletes the desktop entry

**Comment by Pythonic456** [comment]
Ok thanks :)

**Comment by Painadath** [comment]
@Pythonic456 I worked on it but sadly it remains a lot of problems while just installing the desktop entry.

1:how to execute the main.py without knowing the user name.and also the icon
That's why I really against just installing the desktop entry.the more easier and user friendly method is move the complete project to usr/share and it doesn't changes the layout of the project.and adding a remove option in setup.py will be nice.waiting for your reply

**Comment by Pythonic456** [comment]
@Painadath Sure, moving the project to /usr/share/ would be a great idea. Although it does mean setup.py has to be run as root, which might confuse some new users. Except for that, go ahead 👍

**Comment by Painadath** [comment]
@Pythonic456 every single setup.py have to be run as root. And will work on it😀

**Comment by Painadath** [comment]
Almost done.shiuld open the project  please suggest a name for it.i will make the project tommorow (today just playing some windows games in my raspberry pi)

(PS:how do you build the exe in the release)

**Comment by Painadath** [comment]
I meant the pr

**Comment by Pythonic456** [comment]
What do you mean when you say:
> shiuld open the project please suggest a name for it

This project already has a name, are you going to fork it and work on it yourself?
To build the EXE I use PyInstaller, and the latest stable version of this project.

**Comment by Painadath** [comment]
Nope I meant I am going to make a Pr but the Google miss understood it.making a new PR anything to say

**Comment by Pythonic456** [comment]
No I haven't really got anything to say, go ahead and make the PR.

**Comment by Painadath** [comment]
ok added the full functional setup.py with and additional option as remove if you want to rmeove this project 
type this
sudo python3 setup.py remove
@Pythonic456 Please merge

**Comment by Pythonic456** [comment]
@Painadath Is it possible to not have to move the main.py, tktools.py, and the images to another directory, "fedit"? The way I would like this to work is a single addition, a setup.py file that doesn't require me to move the code to a different directory. I am sure you can do this 👍 

Regards,
    @Pythonic456

**Comment by Painadath** [comment]
@Pythonic456 that is possible  I will correct it

**Comment by Painadath** [comment]
Done it

**Comment by Painadath** [comment]
(not tested)

**Comment by Pythonic456** [comment]
Can you update your main.py to the version in my repo? That resolves the last conflict.

**Comment by Painadath** [comment]
After merging you can update the main.py

**Comment by Pythonic456** [comment]
Add-a-setup-py-by-Painadath-·-Pull-Request-3-·-Pythonic456-Fedit

**Comment by Pythonic456** [comment]
It won't let me merge it.

**Comment by Painadath** [comment]
First deletes the main.py in your repo and merge it

**Comment by Pythonic456** [comment]
I would, but your repo is 6 commits behind mine. Can't you just clone my repo again, then add your setup.py, then I can accept a PR. Thanks :)

**Comment by Pythonic456** [comment]
I would, but your repo is 6 commits behind mine. Can't you just clone my repo again, then add your setup.py, then I can accept a PR. Thanks :)

**Comment by Painadath** [comment]
Will do

**Comment by Pythonic456** [comment]
Ok, accepting pull request now. 👍

**Comment by Pythonic456** [comment]
Slight problem. Now we have fedit.png and fedit.desktop in the root directory, and icon.png and icon.svg in data/. I will fix this later. Thanks very much for the setup.py!

**Comment by Painadath** [comment]
@Pythonic456 you have to change the setup.py inorder to remanming fedit.py to main.py 
and desktop entry please edit it

**Pull request merged**
